spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/turbo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
      database: 0

logging:
  level:
    cc.allio.uno: debug
