# 安全配置
turbo:
  secure:
    cipher: turbo
    # 系统加密密钥
    secret-key: efogaWfblI3TK5u1
    # 系统加密算法
    secure-algorithm: aes
    # 忽略认证的接口地址
    skip-list:
      - ${spring.security.oauth2.authorizationserver.endpoint.authorization-uri}
      - ${spring.security.oauth2.authorizationserver.endpoint.token-uri}
      - ${spring.security.oauth2.authorizationserver.endpoint.token-revocation-uri}
      - ${spring.security.oauth2.authorizationserver.endpoint.oidc.client-registration-uri}
      - ${spring.security.oauth2.authorizationserver.endpoint.oidc.user-info-uri}
      - ${spring.security.oauth2.authorizationserver.endpoint.oidc.logout-uri}
      - /login
      - /auth/login # 登陆
      - /oauth2/**  # oauth2 client 相关接口
      - /doc.html
      - /webjars/** # knife4j 静态资源
      - /v3/api-docs/**
      - /auth/captcha # 验证码
      - /sys/tenant/** # 租户
      - /auth/register # 注册
      - /sys/attachment/download/** # 文件下载
      - /sys/attachment/downloadByPath
      - /sys/resource/permanent-token # 永久token
    jwt:
      issuer: https://allio.cc
      subject: token
      # token过期时间
      expire-at: d_1
    captcha:
      # 验证码宽度
      width: 120
      # 验证码高度
      height: 30
      # 验证码字符长度
      length: 4
      # 验证码过期时间
      expire-at: M_5
