spring:
  datasource:
    url: jdbc:postgresql://43.139.180.60:5432/turbo_office
    username: postgres
    password: allio@2024
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 43.139.180.60
      port: 6379
      password: allio@2024
      database: 1

logging:
  level:
    cc.allio.uno: debug
