turbo:
  ob:
    log:
      openobserve:
        # 是否启用日志
        enabled: false
        # 日志服务地址
        endpoint: http://110.42.33.81:5080/api/default/default/_json
        # 组织
        # 日志头
        headers:
          Authorization: "Basic amlhbmd3MTAyN0BnbWFpbC5jb206RmExZFNhU1VaNXByZ3VVbQ=="
          stream-name: "default"
        # 日志发送超时时间
        timeout: 100000
        organization: default
        stream: turbo
    metric:
      exporter:
        # 是否启用metric
        enabled: false
        # 内置metric服务地址
        port: 9464
    trace:
      exporter:
        # 是否启用trace
        enabled: false
        # trace服务地址
        endpoint: http://110.42.33.81:9411/api/v2/spans