turbo:
  oauth2:
    client:
      registration:
        github:
          client-id: id
          client-secret: secret
        gitee:
          client-id: id
          client-secret: secret
      domain: https://localhost:5673/
spring:
  security:
    oauth2:
      authorizationserver:
        endpoint:
          # 授权码
          authorization-uri: /oauth2/authorize
          # token
          token-uri: /oauth2/token
          # revoke
          token-revocation-uri: /oauth2/revoke
          oidc:
            client-registration-uri: /connect/register
            logout-uri: /connect/logout
            user-info-uri: /userinfo