version: '3'
services:
  turbo:
    container_name: turbo
    image: cc/allio/turbo:0.1.0-BETA
    restart: always
    hostname: turbo
    ports:
      - "8600:8600"
    environment:
      TZ: Asia/Shanghai
    networks:
      - allio_net
  turbo-ui:
    container_name: turbo-ui
    image: cc/allio/turbo-ui:0.1.0-BETA
    hostname: turbo-ui
    restart: always
    ports:
      - "8900:8900"
    volumes:
      - /allio/turbo/nginx/conf/:/etc/nginx/conf.d/
      - /allio/turbo/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /allio/turbo/nginx/logs/:/var/log/nginx/
      - /allio/turbo/nginx/cert:/etc/nginx/cert
    networks:
      - allio_net
    depends_on:
      - turbo

networks:
  allio_net:
    external: true