site_name: Turbo文档
repo_name: Turbo
repo_url: https://github.com/ClearXs/Turbo
site_author: J.x (jiangw1027@gmail.com)
copyright: Copyright &copy; 2023 - 2024 ClearX

nav:
  - 首页: index.md

theme:
  # https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
  name: material
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
      primary: indigo
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/brightness-4
      primary: indigo
      accent: grey
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Nunito Sans
    code: Roboto Mono
  logo: favicon.png
  favicon: favicon.png
  features:
    # Navigation
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.instant # some features may not work properly with XHR
    - navigation.tracking # the URL changes with the active anchor
    - navigation.instant.prefetch
    - navigation.tabs # first top-level folders are shown as tabs
    - navigation.tabs.sticky # tabs always show
    - navigation.prune
    - navigation.sections # second-level folders are expanded
    - navigation.expand # all folders are expanded
    - navigation.indexes # link an index page to its parent folder
    - navigation.top # show the back-to-top button
    - toc.integrate # show the table of contents in the navigation panel
    # Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
    - search.suggest # display the likeliest completion for the last word
    - search.highlight # highlight all occurrences
    - search.share # show a share button of the current search
    # Header
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/
    - header.autohide # hide the post title when scroll down
    # Content
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate # add comment to code blocks
    - content.tabs.link # link tabs with the same label
    - content.tooltips

#
# Plugins
#
plugins:
  - tags
  - search: # must be included at the first place
      lang:
        - en
        - zh
      separator: '[\s\u200b\-]'
  - offline
#
# Extensions
#
markdown_extensions:
  - abbr # add a small tooltip to elements
  - admonition # add call-out blocks
  - attr_list # allow to add HTML attributes and CSS classes
  - def_list # add description lists
  - footnotes # define inline footnotes
  - meta # attach arbitrary key-value pairs to a document
  - md_in_html # allow to write Markdown inside HTML elements
  - tables # create tables in Markdown
  - toc: # generate a table of contents from documents
      permalink: '#' # anchor
      toc_depth: 4 # header 1 to header 4
      slugify: !!python/name:pymdownx.slugs.uslugify # convert title to html-compatible text
  - sane_lists # make better lists
  - smarty: # convert some special characters
      smart_angled_quotes: true
  - pymdownx.highlight:
      anchor_linenums: true
      # - pymdownx.betterem: # improve the detection of Markup to emphasize text in Markdown
      # smart_enable: all
  - pymdownx.caret # define superscript
  - pymdownx.mark # highlight text
  - pymdownx.tilde # define subscript
  - pymdownx.critic # track changes
  - pymdownx.details # add collapsible call-outs
  - pymdownx.emoji: # add inlines bundled and custom icons and emojis
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # define code blocks and nesting of code
  - pymdownx.highlight: # highlight of code blocks
      linenums_style: pymdownx-inline
      # anchor_linenums: true # create anchor link on each line of code
  - pymdownx.inlinehilite # highlight inline code blocks
  - pymdownx.smartsymbols # convert some sequences of characters into their corresponding symbols
  - pymdownx.snippets: #  embed content from arbitrary files into a document
      check_paths: true
  - pymdownx.tabbed: # group related content and code blocks under accessible tabs
      alternate_style: true
  - pymdownx.tasklist: # define list of task with checkbox
      custom_checkbox: true
  - pymdownx.escapeall:
      hardbreak: true # use \ to create new line
      nbsp: true # use \<space> to create &nbsp;
  # - pymdownx.keys # syntax ++ctrl+c++ does not look clear in MD document
  - pymdownx.progressbar
extra:
  version:
    provider: mike
  disqus: "vuquangtrong-github-io"