package cc.allio.turbo.modules.developer.constant;

import com.baomidou.mybatisplus.annotation.EnumValue;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * code template language
 *
 * @author j.x
 * @date 2024/5/2 18:39
 * @since 0.1.1
 */
@Getter
@AllArgsConstructor
public enum CodeLanguage {

    APL("apl", "apl"),
    ASCII_ARMOR("asciiArmor", "asciiArmor"),
    ASTERISK("asterisk", "asterisk"),
    C("c", "c"),
    C_SHARP("csharp", "csharp"),
    SCALA("scala", "scala"),
    SOLIDITY("solidity", "solidity"),
    KOTLIN("kotlin", "kotlin"),
    SHADER("shader", "shader"),
    NES_C("nesC", "nesC"),
    OBJECTIVE_C("objectiveC", "objectiveC"),
    OBJECTIVE_CPP("objectiveCpp", "objectiveCpp"),
    SQUIRREL("squirrel", "squirrel"),
    CEYLON("ceylon", "ceylon"),
    DART("dart", "dart"),
    CMAKE("cmake", "cmake"),
    COBOL("cobol", "cobol"),
    COMMON_LISP("commonLisp", "commonLisp"),
    CRYSTAL("crystal", "crystal"),
    CYPHER("cypher", "cypher"),
    D("d", "d"),
    DIFF("diff", "diff"),
    DTD("dtd", "dtd"),
    DYLAN("dylan", "dylan"),
    EBNF("ebnf", "ebnf"),
    ECL("ecl", "ecl"),
    EIFFEL("eiffel", "eiffel"),
    ELM("elm", "elm"),
    FACTOR("factor", "factor"),
    FCL("fcl", "fcl"),
    FORTH("forth", "forth"),
    FORTRAN("fortran", "fortran"),
    GAS("gas", "gas"),
    GHERKIN("gherkin", "gherkin"),
    GROOVY("groovy", "groovy"),
    HASKELL("haskell", "haskell"),
    HAXE("haxe", "haxe"),
    HTTP("http", "http"),
    IDL("idl", "idl"),
    JINJA2("jinja2", "jinja2"),
    MATHEMATICA("mathematica", "mathematica"),
    MBOX("mbox", "mbox"),
    MIRC("mirc", "mirc"),
    MODELICA("modelica", "modelica"),
    MSCGEN("mscgen", "mscgen"),
    MUMPS("mumps", "mumps"),
    NSIS("nsis", "nsis"),
    NTRIPLES("ntriples", "ntriples"),
    OCTAVE("octave", "octave"),
    OZ("oz", "oz"),
    PIG("pig", "pig"),
    PROPERTIES("properties", "properties"),
    PROTOCOL_BUFFERS("protobuf", "protobuf"),
    PUPPET("puppet", "puppet"),
    Q("q", "q"),
    SAS("sas", "sas"),
    SASS("sass", "sass"),
    LIQUID("liquid", "liquid"),
    MERMAID("mermaid", "mermaid"),
    NIX("nix", "nix"),
    SVELTE("svelte", "svelte"),
    SIEVE("sieve", "sieve"),
    SMALLTALK("smalltalk", "smalltalk"),
    SOLR("solr", "solr"),
    SPARQL("sparql", "sparql"),
    SPREADSHEET("spreadsheet", "spreadsheet"),
    ST_EX("stex", "stex"),
    TEXTILE("textile", "textile"),
    TIDDLY_WIKI("tiddlyWiki", "tiddlyWiki"),
    TIKI("tiki", "tiki"),
    TROFF("troff", "troff"),
    TTCN("ttcn", "ttcn"),
    TURTLE("turtle", "turtle"),
    VELOCITY("velocity", "velocity"),
    VERILOG("verilog", "verilog"),
    VHDL("vhdl", "vhdl"),
    WEB_IDL("webIDL", "webIDL"),
    X_QUERY("xQuery", "xQuery"),
    YACAS("yacas", "yacas"),
    Z80("z80", "z80"),
    WAST("wast", "wast"),
    JAVASCRIPT("javascript", "javascript"),
    JSX("jsx", "jsx"),
    TYPESCRIPT("typescript", "typescript"),
    TSX("tsx", "tsx"),
    VUE("vue", "vue"),
    ANGULAR("angular", "angular"),
    JSON("json", "json"),
    HTML("html", "html"),
    CSS("css", "css"),
    PYTHON("python", "python"),
    MARKDOWN("markdown", "markdown"),
    XML("xml", "xml"),
    SQL("sql", "sql"),
    MYSQL("mysql", "mysql"),
    PGSQL("pgsql", "pgsql"),
    JAVA("java", "java"),
    RUST("rust", "rust"),
    CPP("cpp", "cpp"),
    LEZER("lezer", "lezer"),
    PHP("php", "php"),
    GO("go", "go"),
    SHELL("shell", "shell"),
    LUA("lua", "lua"),
    SWIFT("swift", "swift"),
    TCL("tcl", "tcl"),
    YAML("yaml", "yaml"),
    VB("vb", "vb"),
    POWERSHELL("powershell", "powershell"),
    BRAINFUCK("brainfuck", "brainfuck"),
    STYLUS("stylus", "stylus"),
    ERLANG("erlang", "erlang"),
    NGINX("nginx", "nginx"),
    PERL("perl", "perl"),
    RUBY("ruby", "ruby"),
    PASCAL("pascal", "pascal"),
    LIVESCRIPT("livescript", "livescript"),
    LESS("less", "less"),
    SCHEME("scheme", "scheme"),
    TOML("toml", "toml"),
    VB_SCRIPT("vbscript", "vbscript"),
    CLOJURE("clojure", "clojure"),
    COFFEESCRIPT("coffeescript", "coffeescript"),
    JULIA("julia", "julia"),
    DOCKERFILE("dockerfile", "dockerfile"),
    R("r", "r");

    @JsonValue
    @EnumValue
    private final String value;
    private final String label;
}
